## 5 Assignment  
* 행렬 방정식 풀기
  * 다음 행렬 방정식을 'Linear Regression'을 이용해 풀어보자  
    * 적당한 learning rate를 찾아 1000 epoch 정도 계산해본다  
    * 'Pseudo Inverse'를 이용한 풀이와 비교해본다
  * Hint: y = wx 꼴로 변환해본다  
    * Ax=B에서는 x가 미지수이지만, y=wx에서는 w가 미지수임에 주의!
    * linear model에서 b를 없애기 위해서 nn.Linear() 사용법을 검색해보자  
$$Ax=B$$  
$$A=\begin{bmatrix}0&1\\1&1\\2&1\\3&1\\ \end{bmatrix}$$  
$$B=\begin{bmatrix}-1\\0.2\\0.9\\2.1\\ \end{bmatrix}$$

In [ ]:
# 계산을 위해 Numpy ,Pytorch 및 Linear Regression에 쓰이는 함수 호출. nn= neural network를 뜻하고 nn.functional 은 뉴럴 네트워크의 함수, optim은 최적화 작업에 사용된다. 

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as func
import torch.optim as opt

In [ ]:
# 구글 드라이브에 mount하는 함수

#from google.colab import drive
#drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Seed 고정 (Linear Regression이 잘 사용이 되었는지 확인하기 위해 (랜덤성을 줄이기 위해)시드를 고정 시킨다.)
torch.manual_seed(1)

In [ ]:
# Atensor 및 Btensor Data 수동으로 입력하기 및 텐서 찍어보기
x_train = torch.FloatTensor([ [0, 1],
                              [1 ,1],
                              [2, 1],
                              [3, 1] ])
y_train = torch.FloatTensor([[-1], 
                             [0.2], 
                             [0.9], 
                             [2.1] ])


print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[0., 1.],
        [1., 1.],
        [2., 1.],
        [3., 1.]])
torch.Size([4, 2])
tensor([[-1.0000],
        [ 0.2000],
        [ 0.9000],
        [ 2.1000]])
torch.Size([4, 1])


In [ ]:
# Model 초기화 (입력 dim, 출력 dim) (이 문제에서는 ATensor가 입력이므로 입력이 2, 출력이 BTensor이므로 1이다. 또한 bias를 false로 설정함으로써 weight 값만 계산하게 된다.)
model = nn.Linear(2, 1,False)
print(list(model.parameters()))
print(model.parameters())

[Parameter containing:
tensor([[ 0.3643, -0.3121]], requires_grad=True)]
<generator object Module.parameters at 0x7f64476e8250>


In [ ]:
# Optimizer 설정 (learning rate = 0.013으로 설정) , Stochastic gradient descent 모델을 사용하며 Multivariable function 이므로 Learning rate를 0.013으로 한 개의 입력일 때 보다 낮추어 설정한다.
optimizer = opt.SGD(model.parameters(), lr=0.013)

In [ ]:
# 반복 - 가정 값과 실제 값의 cost를 줄이는 과정을 1000번 반복한다. 이때 100번마다 model의 parameter 값을 추출하여
for epoch in range(1000):

  # Cost 계산 / mse_loss(가정에의한값 - 참값, Mean Squared error사용)
  y_hypo = model(x_train)
  cost = func.mse_loss(y_hypo, y_train)

  # cost를 이용해 model update 
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 100번 마다 중간결과 출력
  if epoch % 100 == 99:
    params = list(model.parameters())
    w1 = params[0][0][0].item()
    w2 = params[0][0][1].item()

    print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} Cost: {:.6f}'.format(epoch+1, 1000, w1, w2, cost.item()))
    
    

print(y_hypo-y_train)

Epoch  100/1000 w1: 0.835 w2: -0.597 Cost: 0.058407
Epoch  200/1000 w1: 0.924 w2: -0.788 Cost: 0.022218
Epoch  300/1000 w1: 0.965 w2: -0.875 Cost: 0.014557
Epoch  400/1000 w1: 0.984 w2: -0.916 Cost: 0.012935
Epoch  500/1000 w1: 0.993 w2: -0.934 Cost: 0.012592
Epoch  600/1000 w1: 0.997 w2: -0.943 Cost: 0.012520
Epoch  700/1000 w1: 0.998 w2: -0.947 Cost: 0.012504
Epoch  800/1000 w1: 0.999 w2: -0.948 Cost: 0.012501
Epoch  900/1000 w1: 1.000 w2: -0.949 Cost: 0.012500
Epoch 1000/1000 w1: 1.000 w2: -0.950 Cost: 0.012500
tensor([[ 0.0503],
        [-0.1498],
        [ 0.1500],
        [-0.0501]], grad_fn=<SubBackward0>)


In [ ]:
#저번 과제와 비교
tsA = torch.FloatTensor([[0, 1],
                            [1, 1],
                            [2, 1],
                            [3, 1]])
tsB = torch.FloatTensor([[-1],
                            [0.2],
                            [0.9],
                            [2.1]])

y = torch.inverse(tsA.T.matmul(tsA))
z = tsA.T.matmul(tsB)
x =  y.matmul(z)
k = torch.pinverse(tsA)
x = k.matmul(tsB)
print(x)

tensor([[ 1.0000],
        [-0.9500]])
