## 4 실습 (Assignment 6)  
* 행렬 방정식 풀기 (단, Pytorch만을 사용한다)
  + 다음 행렬 방정식을 'Pseudo inverse matrix'를 이용해 풀어보자
  + $A^TA$의 역행렬이 존재한다고 가정

In [ ]:
import numpy as np
import torch

In [ ]:
# 2x4 크기의TensorA 선언
tsA = torch.FloatTensor([[0, 1],
                            [1, 1],
                            [2, 1],
                            [3, 1]])
# 1x4 크기의 TensorB 선언
tsB = torch.FloatTensor([[-1],
                            [0.2],
                            [0.9],
                            [2.1]])
# tensorA, tensorB 찍어보기 및 transpose 코드 동작 확인
print(tsA)
print(tsB)
print(tsA.T)

tensor([[0., 1.],
        [1., 1.],
        [2., 1.],
        [3., 1.]])
tensor([[-1.0000],
        [ 0.2000],
        [ 0.9000],
        [ 2.1000]])
tensor([[0., 1., 2., 3.],
        [1., 1., 1., 1.]])


In [ ]:
# x구하기 위한 계산 코드

# y는 A^T*A 의 역행렬. 문제에서는 A^T*A의 역행렬이 존재한다고 가정했다.
y = torch.inverse(tsA.T.matmul(tsA))

# z=A^T*B
z = tsA.T.matmul(tsB)

# 최종연산. A^T*A의 역행렬과 A^T*B의 곱연산 
x =  y.matmul(z)

# 찍어보기
print(x)
print(tsA.T.matmul(tsA))
print(torch.inverse(tsA.T.matmul(tsA)))

tensor([[ 1.0000],
        [-0.9500]])
tensor([[14.,  6.],
        [ 6.,  4.]])
tensor([[ 0.2000, -0.3000],
        [-0.3000,  0.7000]])


In [ ]:
# 유사역행렬 코드를 사용해 교차 확인

# tensorA의 유사역행렬 구하기
k = torch.pinverse(tsA)

# tensorA의 유사역행렬과 tensorB 의 곱으로 최종연산
x = k.matmul(tsB)

# 정답 체크
print(x)

tensor([[ 1.0000],
        [-0.9500]])
